### ISSUE TITLE
mysql dump clarification

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [dinkel/docker-backup#1]
Hi,

i didn't find the exact code snippet where the mysql dump is executed. I only want to clarify that the dumping is used with the "--lock-tables" flag?

best,
Christian

**Comment by dinkel** [comment]
Hi Christian,

The command that actually does the backup is found in the [dinkel/btr-backup](https://github.com/dinkel/btr-backup) project here: https://github.com/dinkel/btr-backup/blob/master/backup.d/mysql.sh

As you can see, it does _not_ use "--lock-tables" but "--single-transaction", because I do only use InnoDB tables.

It seems that you are using MyISAM tables then?

**Comment by cguentherTUChemnitz** [comment]
I do not know which type oft tables are used. I tried to use your backup solution for my owncloud container. They have the table lock option noted in the backup guide: 
https://doc.owncloud.org/server/9.0/admin_manual/maintenance/backup.html

besteht,
Christian

**Comment by dinkel** [comment]
My choice of using "--single-transaction" vs. "--lock-tables" is explained here: 

https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_lock-tables

To me, this means that I cannot use both options at the same time, and therefore I chose the one that works well with InnoDB tables, which are (much) more capable and developed more recently. 

One thing about owncloud's backup guide: I would be quite surprised if owncloud used MyISAM tables and not InnoDB. Did you check what types of tables are created by owncloud? Maybe only the guide is "outdated" or they are unnecessarily "safe" with using "--lock-tables".

**Comment by cguentherTUChemnitz** [comment]
Thanks for the clarification. Maybe this detail should be included into the readme, to make the user know about the situation that the backup script is supposed to be used with InnoDB tables.
